version: '3'

services:
  backend:
    build:
     context: backend
     dockerfile: Dockerfile
    ports:
      - "${BACKEND_HOST_PORT}:${BACKEND_DOCKER_PORT}"
    env_file:
      - .env
    networks:
      - network_nextjs_tutorial

networks:
  network_nextjs_tutorial:
    driver: bridge